### PR TITLE
Rubocop it

### PR DESCRIPTION
**Pull request by Uepsilon**
just ran rubocop across the project to get most issues fixed automatically 

👮

### CODE REVIEW

**Comment by DonSchado** [comment]
value? how much? 
¯\_(ツ)_/¯

**Comment by Uepsilon** [comment]
a lot of convenience and a lot of sanity, also: it came at nearly zero costs.

**Comment by jhilden** [comment]
How about directly using Codeclimate?  since this app is open source

**Comment by yoyostile** [comment]
Codeclimate doesn't fix your syntax to comply with your code standards, correct? 
Imho it's a different product. :)

**Comment by Uepsilon** [comment]
yeah it is, still it could provide useful information about code quality changes. not related to this, yet useful

**Pull request closed without merging**
