### PR TITLE
Fix comdirect problem for maxim, swaghetti yolonaise

### PR DESCRIPTION
**Pull request by yoyostile**
@Uepsilon :D

### CODE REVIEW

**Comment by Uepsilon** [comment]
👍

**Comment by yoyostile** [comment]
Merge Merge Merge

**Comment by namxam** [comment]
Selber mergen und deployen! Your PR, your responsibility!

**Comment by yoyostile** [comment]
@Uepsilon @namxam pffff. 👎 


:trollface:

**Pull request merged**
